# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Development and Testing

on: [push, pull_request]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install flask
            pip install app
            pip install psycopg2
            pip install pandas
            pip install requests
    - name: Run tests for Daily Files
      run: python appTestDaily.py
    - name: Run tests for TimeSeries Files
      run: python appTestTimeSeries.py
